// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.Migrations;

/// <summary>
/// Adds the persisted expiration timestamp for the Season 1 Elf Soldier buff.
/// </summary>
public partial class AddCharacterElfSoldierBuffExpirationUtc : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<DateTime>(
            name: "ElfSoldierBuffExpirationUtc",
            schema: "data",
            table: "Character",
            type: "timestamp with time zone",
            nullable: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "ElfSoldierBuffExpirationUtc",
            schema: "data",
            table: "Character");
    }
}
